# Generated by Django 2.2.19 on 2021-03-07 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectplaid', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='users',
            new_name='User',
        ),
    ]
