# Generated by Django 2.2.19 on 2021-03-13 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectplaid', '0002_auto_20210307_1932'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='access_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='item_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
